# Generated by Django 4.2.8 on 2024-02-29 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('item', models.CharField(choices=[('irons', 'Irons'), ('drivers', 'Drivers'), ('woods', 'Woods'), ('putters', 'Putters'), ('wedges', 'Wedges'), ('shirts', 'Shirts'), ('tops', 'Tops'), ('jackets', 'Jackets'), ('trousers', 'Trousers'), ('footwear', 'Footwear'), ('golf balls', 'Golf Balls'), ('hats', 'Hats'), ('trolley', 'Trolleys'), ('gps watches', 'GPS Watches'), ('tees', 'Tees'), ('gloves', 'Gloves')], default='', max_length=50)),
                ('brand', models.CharField(choices=[('adidas', 'Adidas'), ('nike', 'Nike'), ('srixon', 'Srixon'), ('taylormade', 'Taylormade'), ('titleist', 'Titleist'), ('callaway', 'Callaway'), ('footjoy', 'Footjoy'), ('under armour', 'Under Armour'), ('cobra', 'Cobra'), ('motocaddy', 'Motocaddy'), ('ping', 'Ping'), ('mizuno', 'Mizuno'), ('garmin', 'Garmin'), ('calvin klien', 'Calvin Klien'), ('wilson', 'Wilson'), ('bushnell', 'Bushnell'), ('calvin klien', 'Calvin Klien')], default='', max_length=50)),
                ('product_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=2000)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, 400], upload_to='reviews/')),
                ('image_alt', models.CharField(max_length=100)),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
