# Generated by Django 4.2.8 on 2024-03-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='review',
            name='item',
        ),
    ]
