# Generated by Django 4.2.8 on 2024-03-10 18:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_image_url_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, 400], upload_to='reviews/'),
        ),
    ]
