# Generated by Django 4.2.8 on 2024-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lesson'},
        ),
        migrations.AlterField(
            model_name='lessons',
            name='comment',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='golfer',
            field=models.CharField(choices=[('barry power', 'Barry Power'), ('brendan mcdaid', 'Brendan McDaid'), ('david mortimer', 'David Mortimer'), ("shane o'grady", "Shane O'Grady"), ('hazel kavanagh', 'Hazel Kavanagh'), ('john langan', 'John Langan'), ('noel fox', 'Noel Fox')], default='Barry Power', max_length=50),
        ),
    ]
