# Generated by Django 4.2.8 on 2024-05-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessons_options_alter_lessons_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='time',
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
