# Generated by Django 4.2.8 on 2024-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessons_golfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='golfer',
            field=models.CharField(max_length=50),
        ),
    ]
