# Generated by Django 4.2.8 on 2024-03-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lessons_golfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lesson'},
        ),
    ]
