# Generated by Django 4.2.8 on 2024-03-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lessons_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='comment',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='golfer',
            field=models.CharField(choices=[('barry power', 'Barry Power'), ('brendan mcdaid', 'Brendan McDaid'), ('david mortimer', 'David Mortimer'), ("shane o'grady", "Shane O'Grady"), ('hazel kavanagh', 'Hazel Kavanagh'), ('john langan', 'John Langan'), ('noel fox', 'Noel Fox')], default='Barry Power', max_length=50),
        ),
    ]
