# Generated by Django 4.2.8 on 2024-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lessons_comment_alter_lessons_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='comment',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
