# Generated by Django 3.2.24 on 2024-02-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240225_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothing_size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('Extra Large', 'XL'), ('XX Large', '2XL')], default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='degree',
            field=models.CharField(blank=True, choices=[('Forty Six', '46'), ('Forty Eight', '48'), ('Fifty', '50'), ('Fifty Two', '52'), ('Fifty Four', '54'), ('Fifty Six', '56'), ('Fifty Eight', '58'), ('Sixty', '60'), ('Sixty Four', '64')], default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shaft',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('stiff', 'Stiff'), ('senior', 'Senior')], default='Regular', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(blank=True, choices=[('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8'), ('Nine', '9'), ('Ten', '10'), ('Eleven', '11'), ('Twelve', '12'), ('Thirteen', '13')], default='', max_length=8, null=True),
        ),
    ]
