# Generated by Django 4.2.8 on 2024-03-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='clothing_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shaft',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoe_size',
        ),
    ]
